# Generated by Django 5.2.8 on 2025-11-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("channel_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
    ]
