# Generated by Django 5.2.8 on 2025-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tlc", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="message",
            new_name="message_text",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
