# Generated by Django 5.2.8 on 2025-11-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tlc", "0002_rename_message_chatmessage_message_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
