# Generated by Django 5.2.8 on 2025-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tlc", "0003_alter_chatmessage_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
